kubeflow/helm/pipelines/Chart.yaml
kubeflow/helm/pipelines/templates/api-server/requestauthentication.yaml

The RequestAuthentication reosource in the kubeflow namespace is obsolete. It caused IRSA to modify the jwt issuer, leading to the observed exceptions.
This PR is related to issue #146 .
I tested the change by accessing kubeflow pipelines as described in the linked issue.

remove requestauthentication resource

---

bootstrap/helm/bootstrap/Chart.yaml
bootstrap/helm/bootstrap/crds/monitoring.coreos.com_alertmanagerconfigs.yaml
bootstrap/helm/bootstrap/crds/monitoring.coreos.com_alertmanagers.yaml
bootstrap/helm/bootstrap/crds/monitoring.coreos.com_podmonitors.yaml
bootstrap/helm/bootstrap/crds/monitoring.coreos.com_probes.yaml
bootstrap/helm/bootstrap/crds/monitoring.coreos.com_prometheuses.yaml
bootstrap/helm/bootstrap/crds/monitoring.coreos.com_prometheusrules.yaml
bootstrap/helm/bootstrap/crds/monitoring.coreos.com_servicemonitors.yaml
bootstrap/helm/bootstrap/crds/monitoring.coreos.com_thanosrulers.yaml
bootstrap/terraform/equinix-bootstrap/deps.yaml
bootstrap/terraform/equinix-bootstrap/templates/monitoring.coreos.com_servicemonitors.yaml
monitoring/helm/monitoring/Chart.yaml
monitoring/helm/monitoring/values.yaml
monitoring/helm/monitoring/values.yaml.tpl

After upgrade the kube-prometheus-stack, the CRDs in the bootstrap app also needed to be updated. Along with the upgrade, the Grafana dashboard started being deployed in the namespace set by the override, which breaks if Grafana isn't installed in the cluster already.
Test locally with Plural link

upgrade CRDs and fix dashboard deploy namespace

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/main.tf

This PR depends on https://github.com/pluralsh/plural/pull/178. It updates the upstream GKE module, enables the filestore CSI driver and adds the TF outputs to the `deps.yaml` so Plural can process them properly.

update gke module and set tf outputs + enable filestore CSI

---

airbyte/terraform/gcp/main.tf
airbyte/terraform/gcp/terraform.tfvars
airbyte/terraform/gcp/variables.tf
airflow/terraform/gcp/main.tf
airflow/terraform/gcp/terraform.tfvars
airflow/terraform/gcp/variables.tf
bootstrap/terraform/gcp-bootstrap/locals.tf
bootstrap/terraform/gcp-bootstrap/main.tf
bootstrap/terraform/gcp-bootstrap/terraform.tfvars
bootstrap/terraform/gcp-bootstrap/variables.tf
chatwoot/terraform/gcp/main.tf
chatwoot/terraform/gcp/terraform.tfvars
chatwoot/terraform/gcp/variables.tf
gitlab/terraform/gcp/main.tf
gitlab/terraform/gcp/terraform.tfvars
gitlab/terraform/gcp/variables.tf
grafana-tempo/terraform/gcp/main.tf
grafana-tempo/terraform/gcp/terraform.tfvars
grafana-tempo/terraform/gcp/variables.tf
postgres/terraform/gcp/main.tf
postgres/terraform/gcp/terraform.tfvars
postgres/terraform/gcp/variables.tf
sentry/terraform/gcp/main.tf
sentry/terraform/gcp/terraform.tfvars
sentry/terraform/gcp/variables.tf

This PR updates the terraform artifacts for GCP so that the bucket location is set using the new CLI changes from https://github.com/pluralsh/plural-cli/pull/30.

GCP set bucket locations using new CLI

---

.github/actions/vendor/index.js

This PR makes a change to the vendoring action so that it remove registry prefixes while tagging and pushing to our registries.

Remove registry when pushing vendored image

---

bootstrap/terraform/azure-bootstrap/deps.yaml
bootstrap/terraform/azure-bootstrap/variables.tf

This should fix the k8s version variable reference in terraform.
I have ensured that the variable reference is matching across files.

fix aks version variable reference

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/main.tf
bootstrap/terraform/gcp-bootstrap/terraform.tfvars
bootstrap/terraform/gcp-bootstrap/variables.tf

Requires: https://github.com/pluralsh/plural/pull/178
Pins the GKE kubernetes version. Uses Cilium as the CNI. Sets up the same type of node groups as we use on EKS with the same labels. Also deploys the FileStore CSI driver.

GKE: Pin K8s version, use cilium, setup similar node group to EKS

---

airflow/helm/airflow/Chart.yaml
airflow/helm/airflow/values.yaml.tpl

We needed to prefix the minio endpoint with https://.  Otherwise credentials are all properly placed and seems to function.
`plural link helm airflow --name airflow --path ../plural-az-installations/airflow/helm/airflow` and kicked off a dag run to check its logs

Fix airflow azure logs

---

bootstrap/helm/bootstrap/Chart.yaml
bootstrap/helm/bootstrap/templates/cm-shim.yaml
bootstrap/helm/bootstrap/values.yaml

This issue is making some users wait unusually long amounts of time for cert issuance, and is a plausible solve.  Lets see if it works.
plural link to our azure deployment, destroyed and redeployed airflow, confirmed certs were reissued promptly.

Update cert-manager fork to increase clusterissuer timeout

---

hasura/plural/notes.tpl

We don't currently print the hasura admin secrets in the deployment notes, so users have to manually fetch it.
can't test locally unfortunately

add hasura admin secret to notes.tpl

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/main.tf

We currently require people to manually enable gcp apis, which isn't strictly necessary.  This is a first pass on the apis you'll actually need to get going.
tested via local link in our cluster
Close #190

Enable gcp apis needed for deployment in terraform

---

airflow/helm/airflow/Chart.yaml
airflow/helm/airflow/templates/monitors.yaml

I removed the condition based on Postgres for statsd service monitor. This was a mistake I initially introduced. As a result when Postgres is disabled statsd related metrics disappear.
Tested locally using plural link.

Fix Airflow service monitor for external Postgres

---

.gitignore
grafana/helm/grafana/values.yaml

There was a mismatch between the values.yaml file in grafana helm (plural artifacts https://github.com/pluralsh/plural-artifacts/blob/main/grafana/helm/grafana/values.yaml) and the chart file (https://github.com/pluralsh/plural-artifacts/blob/main/grafana/helm/grafana/Chart.yaml) for the app version → 8.3.1 vs 8.3.2.

Grafana 8.3.2

---

vault/helm/vault/Chart.yaml
vault/helm/vault/templates/init-job.yaml
vault/helm/vault/templates/oidc-job.yaml
vault/helm/vault/templates/vault-configmap.yaml
vault/helm/vault/values.yaml
vault/helm/vault/values.yaml.tpl

This PR fixes the Vault admin permissions and adds a script that ensures they are updated before executing following commands. It also changes the OIDC behavior so that the Plural user that deployed Vault gets bound to the admin policy when OIDC is enabled.

Vault: fix vault policy + jobs + set owner to admin

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/variables.tf

Apparently GKE deprecated the patch underneath us, so bumping it along
tested locally

Bump gke version to latest supported patch vsn

---

vault/terraform/gcp/deps.yaml
vault/terraform/gcp/main.tf

Fixes an issue where after a `plural destroy` and redeploy the KMS keyring already exists since these are immutable on GCP. This is a breaking change since for existing users it could lock them out of their Vault deployment.
local linking

vault gcp: ensure keyring is unique as it is immutable

---

.github/workflows/matrix-vendor-and-publish.yml
airflow/plural/recipes/aws-airflow.yaml
airflow/plural/recipes/azure-airflow.yaml
airflow/plural/recipes/gcp-airflow.yaml

airflow is currently not installable in cloud shell, so we should make that explicit
n/a

Fix airflow names, make them restricted

---

airbyte/helm/airbyte/Chart.yaml
airbyte/helm/airbyte/charts/airbyte/templates/bootloader/pod.yaml
airbyte/helm/airbyte/charts/airbyte/templates/scheduler/deployment.yaml
airbyte/helm/airbyte/charts/airbyte/templates/server/deployment.yaml
airbyte/helm/airbyte/charts/airbyte/templates/webapp/deployment.yaml
airbyte/helm/airbyte/charts/airbyte/templates/worker/deployment.yaml

We're seeing occasional issues waiting for airbyte migrations which might be due to race conditions with postgres provisioning, this should serialize the process a bit and make it more reliable/debuggable
tested using plural link

Add postgres wait init containers to airbyte app

---

ingress-nginx/helm/ingress-nginx-private/Chart.yaml
ingress-nginx/helm/ingress-nginx-private/values.yaml
ingress-nginx/helm/ingress-nginx/Chart.yaml
ingress-nginx/helm/ingress-nginx/values.yaml

Taking a look at historical NGINX resource consumption it's apparent the request should be set higher too reduce the number of replicas that are running. Currently it's often scaled too the max number of replicas constantly.

increase nginx memory request

---

ingress-nginx/helm/ingress-nginx-private/Chart.yaml
ingress-nginx/helm/ingress-nginx-private/values.yaml
ingress-nginx/helm/ingress-nginx/Chart.yaml
ingress-nginx/helm/ingress-nginx/values.yaml

Removes the CPU metric from the NGINX HPAs and bumps the memory request on the internal ingress slightly to avoid unneeded scale ups.

remove cpu from nginx HPA

---

bootstrap/terraform/aws-bootstrap/deps.yaml
bootstrap/terraform/aws-bootstrap/main.tf
bootstrap/terraform/aws-bootstrap/output.tf
bootstrap/terraform/aws-bootstrap/terraform.tfvars
bootstrap/terraform/aws-bootstrap/variables.tf

This PR outputs the complete VPC object from our AWS bootstrap terraform and allows users to create database subnets. Users can do this by adding a list of subnets under the `database_subnets` key for bootstrap in the `context.yaml`. For example:
```yaml
spec:  
configuration:
bootstrap:
database_subnets:
- "10.0.64.0/24"
```

Bootstrap AWS: output complete vpc object and allow for enabling db subnets

---

bootstrap/helm/plural-certmanager-webhook/Chart.yaml
bootstrap/helm/plural-certmanager-webhook/values.yaml

Updates the image for our cert-manager webhook to the one that uses our new Go client.
Deployed a new cluster using Plural DNS that uses this image and check if cert-manager is able too create certificates properly.

use cert-mgr webhook with new Go client

---

jitsu/helm/jitsu/Chart.yaml
jitsu/helm/jitsu/templates/deployment.yaml
jitsu/helm/jitsu/templates/secret.yaml
jitsu/helm/jitsu/values.yaml.tpl

Dignifi health are requesting this to be set up
tested using plural link

Add SMTP configuration for jitsu

---

argo-workflows/helm/argo-workflows/Chart.yaml
argo-workflows/helm/argo-workflows/templates/serviceaccount.yaml
argo-workflows/helm/argo-workflows/templates/workflow-rbac.yaml
argo-workflows/helm/argo-workflows/values.yaml
argo-workflows/helm/argo-workflows/values.yaml.tpl
argo-workflows/plural/recipes/argo-workflows-aws.yaml
argo-workflows/plural/recipes/argo-workflows-azure.yaml
argo-workflows/plural/recipes/argo-workflows-gcp.yaml

Argo has the capability to provide a default role to sso users, which can naturally be made a RO role so users can use the workflow dashboard for visibility.  We should configure that properly by default.
verified with plural link

Add default read-only role to argo-workflow sso

---

bootstrap/terraform/aws-bootstrap/deps.yaml
bootstrap/terraform/aws-bootstrap/main.tf
bootstrap/terraform/aws-bootstrap/variables.tf

When an AWS region only has 2 availability zones a duplicate name for our node groups occurs. This PR uses a new version of our node group module that appends the subnet name to the node group name to ensure they are unique. Since this is a breaking change, this is also a good opportunity to update the AMI used by the worker nodes. Also, the `kube-proxy` and `vpc-cni` versions are updated.
local linking

AWS: ensure node groups have a unique name

---

postgres/helm/postgres/Chart.yaml
postgres/helm/postgres/crds/operatorconfigurations.yaml
postgres/helm/postgres/crds/postgresqls.yaml
postgres/helm/postgres/crds/postgresteams.yaml
postgres/helm/postgres/values.yaml
postgres/helm/postgres/values.yaml.tpl

This PR updates the postgres operator to the latest version along with a modification that allows for setting liveness probes for databases. This should fix issues where patroni can't talk to the Kubernetes API anymore. It also uses a newer Spilo image that fixes the backup retention policy which wasn't working. Another small fix is that the operator will now add the necessary annotation for IRSA to service accounts it creates for the postgres pods (so this doesn't need to be done with terraform anymore).
Local linking. 
- Check that backups are pushed to S3.
- Check that WAL archives are pushed to S3.
- Check that old backups are cleaned up.
- Check that there aren't any errors in the `pg_log` logs (related to send WAL archives to S3)

Use forked postgres operator with liveness probes and fix backup lifecycle

---

bootstrap/helm/bootstrap/Chart.yaml
bootstrap/helm/bootstrap/templates/configmap.yaml
bootstrap/helm/bootstrap/templates/operator.yaml
bootstrap/helm/bootstrap/templates/rbac.yaml
bootstrap/helm/bootstrap/values.yaml

This PR updates the Plural operator which includes the new global pull credentials and the ability to restart pods that have an Oauth2-Proxy sidecar injected when either the sidecar configmap or secrets change.
Local linking. Testing by changing either the global oauth-proxy configmap or the oauth2-proxy secret from which the environment variables are loaded.

Operator oauth sidecar reloading

---

bootstrap/terraform/aws-bootstrap/deps.yaml
bootstrap/terraform/aws-bootstrap/variables.tf

Make the spot node groups we create on AWS multi-zoned to reduce the overall amount of node groups we create.
Local linking.

AWS: make spot node groups multi zoned

---

airbyte/helm/airbyte/Chart.yaml
airbyte/helm/airbyte/templates/_helpers.tpl
airbyte/helm/airbyte/templates/metrics.yaml
airbyte/helm/airbyte/templates/prometheusrule.yaml
airbyte/helm/airbyte/values.yaml
monitoring/helm/monitoring/Chart.yaml
monitoring/helm/monitoring/templates/opentelemetry-collector.yaml
monitoring/helm/monitoring/values.yaml

Configures the otel collector to accept grpc and sets up an exporter with airbyte's prebaked image to begin shipping/alarming on airbyte metrics
tested with plural link

Add airbyte metrics exporter

---

ray/helm/kuberay-operator/Chart.yaml
ray/helm/kuberay-operator/values.yaml
ray/helm/ray/Chart.yaml
ray/helm/ray/templates/raycluster-cluster.yaml
ray/helm/ray/templates/secrets.yaml
ray/helm/ray/values.yaml
ray/helm/ray/values.yaml.tpl

Allow for easily adding a git-sync sidecar container for the ray head server to sync in python code that should be executed.
Local linking.

Ray: add support for git-sync

---

grafana-tempo/helm/grafana-tempo/Chart.yaml
grafana-tempo/helm/grafana-tempo/templates/grafana-datasource.yaml
grafana-tempo/helm/grafana-tempo/values.yaml
grafana-tempo/helm/grafana-tempo/values.yaml.tpl
grafana/helm/grafana/Chart.yaml
grafana/helm/grafana/values.yaml.tpl
loki/helm/loki/Chart.yaml
loki/helm/loki/templates/grafana-datasource.yaml
monitoring/helm/monitoring/Chart.yaml
monitoring/helm/monitoring/templates/grafana-datasource.yaml
monitoring/helm/monitoring/values.yaml
monitoring/helm/monitoring/values.yaml.tpl

Currently, if people deploy our Loki app the one bundled in monitoring will also still run. This PR disables the simple Loki setup in the monitoring app if the dedicated Loki app is installed.
Local linking

disable simple loki if distributed loki is deployed

---

bootstrap/terraform/aws-bootstrap/deps.yaml
bootstrap/terraform/aws-bootstrap/s3-vpc-endpoint.tf
bootstrap/terraform/aws-bootstrap/terraform.tfvars
bootstrap/terraform/aws-bootstrap/variables.tf

add s3 vpc endpoint to route traffic from within the cluster to S3 without going to the public internet.

add s3 vpc endpoint

---

bootstrap/helm/bootstrap/Chart.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_configurationoverlays.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_dashboards.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_defaultstorageclasses.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_licenses.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_logfilters.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_logtails.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_proxies.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_registrycredentials.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_resourcegroups.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_runbooks.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_secretsyncs.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_slashcommands.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_statefulsetresizes.platform.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_wireguardpeers.vpn.plural.sh.yaml
bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_wireguardservers.vpn.plural.sh.yaml
bootstrap/helm/bootstrap/templates/rbac.yaml
bootstrap/helm/bootstrap/values.yaml

This PR updates the bootstrap helm chart to use the latest plural operator that includes the ability to create a Wireguard VPN and add peers to the VPN.
Local linking.

Update bootstrap for VPN operator

---

grafana/helm/grafana/Chart.yaml
grafana/helm/grafana/templates/smtp-secret.yaml
grafana/helm/grafana/values.yaml
grafana/helm/grafana/values.yaml.tpl

Adds SMTP settings to Grafana so that users can be invited.
Local linking

Add SMTP settings to Grafana

---

grafana/helm/grafana/Chart.yaml
grafana/helm/grafana/values.yaml

There's a severe vulnerability in grafana pre 9.2.4 that we need to patch
Closes #434
local link

Bump grafana to 9.2.4 to fix security vuln

---

airbyte/helm/airbyte/Chart.yaml
airbyte/helm/airbyte/values.yaml

This allows us to support otel properly and should have been done regardless
local link, confirmed a sync can be started

Bump airbyte to 0.39.42

---

airbyte/helm/airbyte/Chart.yaml
airbyte/helm/airbyte/charts/airbyte/templates/pod-sweeper/configmap.yaml
airbyte/helm/airbyte/charts/airbyte/templates/pod-sweeper/sweeper-helpers.tpl
airbyte/helm/airbyte/charts/airbyte/values.yaml

Adds the ability to modify the pod sweeper timeouts for your airbyte instance with:
```
airbyte:
podSweeper:
timeouts:
success: ...
failure: ...
```
We should probably find a way to deprecate this script entirely though as it's somewhat crap
verified in a local link

Add customizable pod sweeper setup

---

n8n/helm/n8n/Chart.yaml
n8n/helm/n8n/templates/deployment.yaml
n8n/helm/n8n/templates/secret.yaml
n8n/helm/n8n/values.yaml
n8n/helm/n8n/values.yaml.tpl

add ability to read smtp config and store them in an env secret
local link

Add smtp setup for n8n

---

airbyte/helm/airbyte/Chart.yaml
airbyte/helm/airbyte/charts/airbyte/templates/env-secret.yaml

Some env vars being present but empty are significant in log4j setup in airbyte due to misconfigured defaults, as defined here: https://github.com/airbytehq/airbyte/blob/master/airbyte-commons/src/main/resources/log4j2.xml
Change how we default the env vars to not hit that footgun

Fix log4j configuration on airbyte

---

jitsu/helm/jitsu/Chart.yaml
jitsu/helm/jitsu/templates/deployment.yaml
jitsu/helm/jitsu/templates/secret.yaml
jitsu/helm/jitsu/values.yaml
jitsu/helm/jitsu/values.yaml.tpl

Summary:
Adding docker-in-docker-daemon.
It helps **jitsu** to get access to sources through **airbyte**

Adding docker-in-docker container into jitsu deployment

---

dagster/terraform/gcp/deps.yaml
dagster/terraform/gcp/main.tf

We didn't wire in the service account name into the workload-identity module, which i believe causes terraform to race.
local link, confirmed no terraform changes

Fix dagster service account ordering

---

ghost/helm/ghost/Chart.yaml
ghost/helm/ghost/values.yaml

This PR uses the newly vendored image for Ghost and bumps the image version. In the future, when a new version of Ghost is pushed Renovate should create a PR to update it.
Local linking.

fix(ghost): use correct vendored image and bump version

---

bootstrap/helm/bootstrap/templates/plural-issuer.yaml
bootstrap/helm/bootstrap/values.yaml
bootstrap/helm/bootstrap/values.yaml.tpl

Also take the opportuntity to give it a plural specific name.  I'll add a context option to make this globally enabled so we can start migrating apps to it.
local link, verified issuer can be created/recreated

Add google ACME issuer

---

gitlab/plural/recipes/aws-gitlab.yaml
gitlab/plural/recipes/gcp-gitlab.yaml
gitlab/repository.yaml

a user who recently tried to set up gitlab realized these were incorrect, this should fix
verified locally

Add correct uriFormats for gitlab

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/main.tf
bootstrap/terraform/gcp-bootstrap/variables.tf

really trivial change, but lets people customize it

Expose GKE release channel in gcp bootstrap

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/main.tf
bootstrap/terraform/gcp-bootstrap/variables.tf

Exposing this toggle, with clear language that it will force control plane recreation.
plural link

Add ability to toggle between regional/zonal gke clusters

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/variables.tf

The current version set for GKE isn't supported anymore and people using the cloud demo are not able to create a cluster because of this. This PR bumps the GKE version so that clusters can be created again.
Local linking

chore(bootstrap): bump gke to a valid version

---

.github/workflows/matrix-vendor-and-publish.yml
airbyte/plural/docs/basic-auth.md
airbyte/plural/docs/bring-your-own-db.md
airbyte/repository.yaml
airflow/plural/docs/bring-your-db.md
airflow/plural/docs/pip-packages.md
airflow/repository.yaml
superset/plural/docs/pip-packages.md
superset/repository.yaml

These are the docs I remember having the most customization requests.  We can probably add more but this is a great starting point.
n/a

Add app docs for airflow, airbyte, superset

---

postgres/terraform/aws/deps.yaml
postgres/terraform/aws/main.tf
postgres/terraform/aws/variables.tf

This PR enables AES256 encryption of the S3 bucket used for base backups and wal archives of postgres clusters managed by the operator.
Deployed using local linking and checked that current base backups and wal archives are still appearing in the S3 bucket as expected.

feat(postgres): enable AES256 bucket encryption on AWS

---

bootstrap/helm/bootstrap/Chart.yaml
bootstrap/helm/bootstrap/templates/issuer.yaml
bootstrap/helm/bootstrap/values.yaml

Will help with some byok clusters too
link

Make cert-manager disable-able

---

airbyte/plural/notes.tpl
dagster/plural/notes.tpl

This will tell non-oidc users why they can't access the web ui
n/a

Add oidc notes for airbyte + dagster

---

bootstrap/terraform/aws-bootstrap/deps.yaml
bootstrap/terraform/aws-bootstrap/main.tf

After the BYOK PR, adding custom multi-az node groups is broken. This PR should fix it.

fix multi-az node groups

---

ray/terraform/aws/deps.yaml
ray/terraform/aws/main.tf
ray/terraform/aws/variables.tf

This PR updates the aws node groups you can deploy alongside Ray to K8s 1.22, which we recently updated to.
Local linking.

chore(ray): update aws node groups to k8s 1.22

---

superset/helm/superset/Chart.yaml
superset/helm/superset/values.yaml

The default superset uses is teeny (5), and we see it frequently getting saturated.  This might help.
local link

Bump superset pool size

---

n8n/helm/n8n/Chart.yaml
n8n/helm/n8n/templates/deployment.yaml
n8n/helm/n8n/templates/secret.yaml
n8n/helm/n8n/values.yaml
n8n/helm/n8n/values.yaml.tpl

Apparently this is regen'ed on boot, so passing it explicitly is a must
local link

Stabilize n8n encryption key

---

datahub/helm/datahub/Chart.yaml
datahub/helm/datahub/values.yaml

This was set far too strictly and caused xendits frontend to crash frequently.  Giving it some more headroom for now.
link

Bump datahub frontend limit

---

ray/terraform/aws/deps.yaml
ray/terraform/aws/main.tf

Allows for changing the instance type of ray node groups without running into problems. The new upstream commit has the `create_before_destroy` lifecycle policy set to false which would avoid issues with the node group already existing when it needs to be recreated like when changing the instance types.

fix(ray): allows for changing the instance type

---

monitoring/helm/monitoring/Chart.yaml
monitoring/helm/monitoring/values.yaml

It's not really being used meaningfully, and it's caused a few failed installs so disable it until there's a better solve
link

Disable opentelemetry

---

monitoring/helm/monitoring/Chart.yaml
monitoring/helm/monitoring/values.yaml

The extra label being added to alerts breaks the ability to use the namespace label to sort alerts coming from a particular namespace. This PR removes the added namespace label from alerts so it is possible to filter alerts coming from a particular namespace.

remove namespace alert label

---

bootstrap/terraform/aws-bootstrap/deps.yaml
bootstrap/terraform/aws-bootstrap/variables.tf

This PR updates the EKS node groups to the latest AMI image for K8s 1.23.
Local linking.

bootstrap: update aws eks node groups to 1.23

---

.github/workflows/matrix-vendor-and-publish.yml
.github/workflows/matrix-vendor-cron.yml
.github/workflows/vendor-app.yml

Logging in to ECR wasn't working since it is not available in `us-east-2`, changing the region to `us-east-1` fixes it. This PR fixes it so we can vendor images hosted on ECR.

fix(ci): allow for vendoring images from aws ecr

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/variables.tf

This PR updates our GCP bootstrap K8s version to the latest for 1.23. After looking in the GCP console it looks like the clusters we are deploying are already on `1.23.14-gke.1800`, which GCP likely upgraded to automatically for compatibility or security reasons, so this should actually only be a small update.
Local linking

deps(boostrap): bump gcp k8s to 1.23

---

bootstrap/helm/plural-certmanager-webhook/Chart.yaml
bootstrap/helm/plural-certmanager-webhook/values.yaml
bootstrap/terraform/kind-bootstrap/deps.yaml
bootstrap/terraform/kind-bootstrap/variables.tf

bump plural-certmanager-webhook and k8s kind version
This PR fixes the problem: `E0228 13:53:48.071853      11 controller.go:116] loading OpenAPI spec for "v1alpha1.acme.plural.sh" failed with: OpenAPI spec does not exist`

bump plural-certmanager-webhook and k8s kind version

---

metabase/helm/metabase/Chart.yaml
metabase/helm/metabase/values.yaml

Upgrade Metabase artifact to use [latest release](https://github.com/metabase/metabase/releases/tag/v0.45.3).
Tested locally on dev cluster.

Metabase upgrade

---

airflow/helm/airflow/Chart.yaml
airflow/helm/airflow/values.yaml.tpl
sentry/terraform/gcp/deps.yaml
sentry/terraform/gcp/main.tf

I think bad knownhosts files might actually be the cause of some airflow setup failures, and if people really want the assurance, they can always just reconfigure it in their `values.yaml` file
local link

Don't set known hosts by default for airflow

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/main.tf
bootstrap/terraform/gcp-bootstrap/variables.tf

- Added variable to grant generated node service accounts role to pull images from Google Container Registry, default to false
- Set the variable to true and was able to pull image from a private container registry on the same project

feat(bootstrap-gcp): add variable to allow gke to pull image from container registry

---

airbyte/terraform/gcp/deps.yaml
airbyte/terraform/gcp/main.tf
airbyte/terraform/gcp/variables.tf

- Added GCP SA bound to default K8S sa on airbyte namespace to be able to add specific roles
- Added a BigQuery data editor and a BigQuery user to the roles of this new sa and tested a job sync on airbyte with BigQuery as destination

feat(airbyte-gcp): add airbyte workload identity sa

---

.github/workflows/matrix-vendor-and-publish.yml
grafana-agent/repository.yaml
loki/helm/loki/values.yaml.tpl
mimir/helm/mimir/values.yaml.tpl
mimir/repository.yaml
monitoring/helm/monitoring/values.yaml.tpl
trace-shield/helm/trace-shield/Chart.yaml
trace-shield/helm/trace-shield/values.yaml
trace-shield/repository.yaml

The yaml key for the release status was incorrect. This PR fixes setting these applications as alpha.

fix: use the correct yaml key for release status

---

loki/helm/loki/Chart.yaml
loki/helm/loki/values.yaml.tpl
mimir/helm/mimir/Chart.yaml
mimir/helm/mimir/values.yaml.tpl
monitoring/helm/monitoring/Chart.yaml
monitoring/helm/monitoring/values.yaml.tpl
trace-shield/helm/trace-shield/Chart.yaml
trace-shield/helm/trace-shield/deps.yaml
trace-shield/plural/recipes/trace-shield-aws.yaml
trace-shield/plural/recipes/trace-shield-azure.yaml
trace-shield/plural/recipes/trace-shield-gcp.yaml

Adds grafana-agent as a dependency for trace shield and fixes some other application templates.

fix: add grafana agent as dependency + fix some templates

---

.github/workflows/matrix-vendor-and-publish.yml
.github/workflows/semantic-pr.yaml
release.config.js

This PR sets up semantic release (plus) that will allow us to create new Git tags and GitHub releases for changes to applications. The versioning has no relation to the versioning of packages within an application's artifact and is purely there to track historical changes to applications. Since this uses semantic release, and action is added that enforces semantic PR titles since those are needed for semantic release so it can create the next version.

ci: setup semantic release for applications

---

.github/workflows/matrix-trivy-scan.yml
.github/workflows/matrix-vendor-and-publish.yml
grafana-agent/helm/grafana-agent/Chart.yaml
grafana-agent/helm/grafana-agent/values.yaml.tpl
trace-shield/helm/trace-shield/Chart.yaml
trace-shield/helm/trace-shield/values.yaml
trace-shield/helm/trace-shield/values.yaml.tpl

Some of the ingresses for Trace Shield weren't being templated properly. Also, the tenant header for the grafana agent wasn't being set properly.

fix(trace-shield): set all ingress hostnames

---

dagster/Dockerfile
dagster/helm/dagster/Chart.yaml
dagster/helm/dagster/values.yaml
dagster/helm/dagster/values.yaml.tpl
dagster/terraform/gcp/deps.yaml
dagster/terraform/gcp/main.tf
dagster/terraform/gcp/terraform.tfvars
dagster/terraform/gcp/variables.tf

- Fixed GCSComputeLogManager 
- Fixed gcp service account
- Fixed dagster bucket location
- Fixed user-code-example container image for gcp
- Remove dagster-aws-env for gcp

fix(dagster-gcp): fix dagster config on gcp

---

mimir/helm/mimir/Chart.yaml
mimir/helm/mimir/values.yaml

This PR increases the Mimir PVCs to the size recommended for small deployments. Particularly the compactor storage was causing problems.
Local linking.

fix(mimir): increase PVC size to recommended small

---

directus/helm/directus/Chart.yaml
directus/helm/directus/deps.yaml
directus/helm/directus/templates/deployment.yaml
directus/helm/directus/templates/secret.yaml
directus/helm/directus/values.yaml
directus/helm/directus/values.yaml.tpl
directus/plural/notes.tpl
directus/plural/recipes/directus-aws.yaml
directus/plural/recipes/directus-azure.yaml
directus/plural/recipes/directus-gcp.yaml
directus/repository.yaml
directus/terraform/gcp/deps.yaml
directus/terraform/gcp/main.tf
directus/terraform/gcp/outputs.tf
directus/terraform/gcp/terraform.tfvars
directus/terraform/gcp/variables.tf

- Added OIDC (OIDC users should be manually added to a role using the admin user)
- Added default admin user
- Added GCS storage backend (need to add AWS and Azure later)
- Fixed postgres connection
Local linking
Users who log in via OIDC are not automatically admin. They have to be added to a specific role by the admin. We can set the default role of the OIDC users but not knowing the uuid of the admin role (and not being able to set it manually), it is complicated to make the OIDC users be admin by default.
We can get the Admin role uuid from the api but how to inject the `AUTH_<PROVIDER>_DEFAULT_ROLE_ID` environment variable? Any suggestion @michaeljguarino

feat(directus): oidc + default admin account + gcs backend

---

bootstrap/helm/bootstrap-operator/Chart.yaml
bootstrap/helm/bootstrap-operator/crds/bootstrap.plural.sh_bootstraps.yaml
bootstrap/helm/bootstrap-operator/values.yaml
bootstrap/helm/bootstrap-operator/values.yaml.tpl
bootstrap/plural/recipes/gcp-cluster-api.yaml
bootstrap/terraform/gcp-bootstrap-cluster-api/deps.yaml
bootstrap/terraform/gcp-bootstrap-cluster-api/main.tf

feat: Add cluster api bootstrap for GCP

---

dagster/helm/dagster/Chart.yaml
dagster/helm/dagster/values.yaml

These aren't enabled by default apparently and can leave the dagster db stale
local link on our install

feat: Enable dagster in-chart migrations

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/variables.tf

1.23 is fully deprecated, making demo projects unavailable.  Just need to get this out

feat(bootstrap): Bump GKE version

---

bootstrap/helm/bootstrap/Chart.yaml
bootstrap/helm/bootstrap/templates/issuer.yaml

In my Plural cluster, I have disabled public nginx ingress to avoid running a worldwide open listener (for multiple reasons it's not possible to restrict traffic in this configuration). Instead I'm using AWS ALB with AWS ACM certificate as public ingresses. The Let's Encrypt certs that are provisioned by default are not used, which is a waste of public resources and leaks information (issued LE certificates are listed in the public Certificate Transparency records).
I don't want to completely disable certificate-manager. Multiple apps refer to `letsencrypt-prod` ClusterIssuer and removing the LE ClusterIssuers without changing all these apps would leave them permanently slightly broken and certificate-manager would keep trying to provision the certs. To make things simple, this change …

feat(bootstrap): disable Let's Encrypt ClusterIssuers when acmeServer is unset

---

bootstrap/helm/bootstrap-operator/Chart.yaml
bootstrap/helm/bootstrap-operator/crds/azure-identity.yaml
bootstrap/helm/bootstrap-operator/templates/azure.yaml
bootstrap/helm/bootstrap-operator/values.yaml
bootstrap/helm/bootstrap-operator/values.yaml.tpl
bootstrap/plural/recipes/azure-cluster-api.yaml
bootstrap/terraform/azure-bootstrap-cluster-api/deps.yaml
bootstrap/terraform/azure-bootstrap-cluster-api/main.tf
bootstrap/terraform/azure-bootstrap-cluster-api/terraform.tfvars
bootstrap/terraform/azure-bootstrap-cluster-api/variables.tf

Adds support for Azure CAPI. See https://github.com/pluralsh/bootstrap-operator/pull/23.
Also pushed some changes to https://github.com/pluralsh/plural-cli/tree/bootstrap to pass context values.
CAPI docs: https://capz.sigs.k8s.io/topics/managedcluster.html
Notes:
- `aadpodidentity.k8s.io` CRDs are registered temporarily as we depend on bootstrap recipe.
- Once CAPI will be the default we can move client ID and secret from recipe to CLI survey.
```
plural init
plural bundle install bootstrap azure-cluster-api
plural build --cluster-api
plural deploy
```

feat: Add support for Azure CAPI

---

trace-shield/helm/trace-shield/Chart.yaml
trace-shield/helm/trace-shield/templates/oathkeeper-rules.yaml
trace-shield/helm/trace-shield/values.yaml

Fixes: https://github.com/pluralsh/trace-shield/issues/34
For using and OAuth 2.0 Client as the way to authenticate a Grafana datasource we need to be able to send the Client ID and Secret in the basic auth header.

fix(trace-shield): Allow oauth credentials in basic auth header

---

ghost/helm/ghost/values.yaml

Small fixup PR that solves pushing to Plural.

fix(ghost): allow for plural apply

---

bin/artifact-renovate-script.sh
renovate.json

This PR updates the renovate config so it will group the updates for new applications. It also adds the script used to update the renovate config so it can be run more easily.

ci: update renovate config

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/variables.tf

fix: Bump gke version to recent supported version

---

yatai/helm/yatai/Chart.yaml
yatai/helm/yatai/values.yaml

The service for the conversion webhook in the CRD was incorrect. This PR fixes it so the Kubernetes API can access the conversion webhook service properly.

fix(yatai): set release name for CRD webhook

---

bin/artifact-renovate-script.sh
renovate.json

This reverts commit 79c4d532eb2214878d2288d91c2e0b894b7fba6d.
The version of renovate we use doesn't support the new value yet.

ci: revert renovate config update

---

.github/workflows/matrix-vendor-and-publish.yml

After configuring the same commit analyzer we use on other repos the CI failed. This PR should fix it.

ci: fix installing commit analyzer

---

mlflow/terraform/aws/deps.yaml
mlflow/terraform/aws/main.tf
mlflow/terraform/aws/variables.tf

This PR allows users to add tags to the MLFlow S3 bucket easily.
Local linking

feat(mlflow): allow adding tags to s3 bucket

---

trace-shield/helm/trace-shield/Chart.yaml
trace-shield/helm/trace-shield/values.yaml

Bumps trace shield with a fix for using an auth header to access the API.

fix(trace-shield): allow auth header

---

metabase/helm/metabase/Chart.yaml
metabase/helm/metabase/values.yaml
metabase/vendor_images.yaml

This will help handle a security vuln for metabase we need to path.
Fixes #781
link

Upgrade metabase to v0.46.6 and add path image to vendor list

---

mlflow/plural/docs/basic-auth.md
mlflow/repository.yaml

This is basically copypasta from the airbyte docs since they're effectively the same.
n/a

feat: Add docs for mlflow basic auth

---

mlflow/plural/docs/bucket-versioning.md
mlflow/terraform/aws/deps.yaml
mlflow/terraform/aws/main.tf
mlflow/terraform/aws/variables.tf

The underlying terraform module supports this, but we didn't add the plumbing to be able to wire it in.
link

feat: Support mlflow object versioning

---

posthog/helm/posthog/Chart.yaml
posthog/helm/posthog/values.yaml

Apparently the plugin server will sometimes perpetually OOM on boot, this should help
n/a

Double posthog plugin mem limit

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/variables.tf

Looks like this got pulled on us again.
link

feat(bootstrap): Fix deprecated gke version

---

airbyte/helm/airbyte/Chart.yaml
airbyte/helm/airbyte/values.yaml.tpl
airbyte/terraform/gcp/deps.yaml
airbyte/terraform/gcp/main.tf
airbyte/terraform/gcp/outputs.tf

Now that airbyte uses the configured service account (and no more default) when spawning pods, we need to configure workload identity properly
Local link + deploy
Tested with a BigQuery destination (with ADC and roles configured on gcp sa)

fix(airbyte): fix workload identity

---

bootstrap/terraform/aws-bootstrap/deps.yaml
bootstrap/terraform/aws-bootstrap/main.tf
bootstrap/terraform/aws-bootstrap/s3-vpc-endpoint.tf
bootstrap/terraform/aws-bootstrap/variables.tf

This PR upgrade the Kubernetes version for our AWS EKS deployments to 1.24 since the EOL is coming up. It also takes the opportunity of this breaking change to improve the VPC and subnet configuration a bit. While working on our migration to Cluster API an issue was observed where the migration got stuck as the CAPA pod lost communication to AWS while it was shuffling around the NAT gateways and route tables of the subnets the workers are deployed in. The reason to have a NAT gateway in each subnet is to avoid cross AZ ingress/egress charges for any data going to/from the public internet. Applying this change to the networking setup as part of the Terraform should help ensure the migration to CAPI is more smooth.
Local linking

feat(bootstrap): upgrade AWS EKS to K8s 1.24 + NAT improvements

---

ray/terraform/aws/deps.yaml
ray/terraform/aws/variables.tf

This PR upgrade the node groups used by Ray to Kubernetes 1.23.

fix(ray): upgrade eks node groups to 1.23

---

bootstrap/plural/docs/custom-launch-template.md
bootstrap/repository.yaml

Add docs for how to customize the launch templates of your EKS node groups.
n/a

docs(bootstrap): add launch template docs for aws

---

airflow/helm/airflow/Chart.yaml
airflow/helm/airflow/values.yaml.tpl
argo-workflows/helm/argo-workflows/Chart.yaml
argo-workflows/helm/argo-workflows/values.yaml.tpl
bootstrap/helm/bootstrap/Chart.yaml
bootstrap/helm/bootstrap/templates/defaultstorageclass.yaml
bootstrap/helm/bootstrap/templates/snapshot.yaml
bootstrap/helm/bootstrap/values.yaml.tpl
chatwoot/helm/chatwoot/Chart.yaml
chatwoot/helm/chatwoot/values.yaml.tpl
gitlab/helm/gitlab/Chart.yaml
gitlab/helm/gitlab/values.yaml.tpl
growthbook/helm/growthbook/Chart.yaml
growthbook/helm/growthbook/values.yaml.tpl
harbor/helm/harbor/Chart.yaml
harbor/helm/harbor/values.yaml.tpl
loki/helm/loki/Chart.yaml
loki/helm/loki/values.yaml.tpl
mimir/helm/mimir/Chart.yaml
mimir/helm/mimir/values.yaml.tpl
postgres/helm/postgres/Chart.yaml
postgres/helm/postgres/values.yaml.tpl
sftpgo/helm/sftpgo/Chart.yaml
sftpgo/helm/sftpgo/values.yaml.tpl
vault/helm/vault/Chart.yaml
vault/helm/vault/values.yaml.tpl

This PR updates various applications to ensure that both `google` and `gcp` can be returned as the `.Provider` by our CLI while we finish the provider name migration.

fix: allow both google and gcp provider

---

bootstrap/plural/recipes/azure-k8s.yaml

This PR adds Azure Workload Identity to the regular Azure recipe so new users will also have it installed.

feat(bootstrap): add azure workload identity to recipe

---

ray/terraform/aws/deps.yaml
ray/terraform/aws/variables.tf

This PR upgrades the Ray node groups to EKS 1.24.

feat(ray): upgrade to aws eks 1.24

---

bootstrap/terraform/aws-bootstrap/deps.yaml
bootstrap/terraform/aws-bootstrap/variables.tf

This PR bumps the addons for AWS clusters. The VPC CNI addon needs to be bumped to `1.13` before it can be bumped to the latest `1.14` version.

feat(bootstrap): bump aws addon versions

---

bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/variables.tf

Bumped Kubernetes patch version for GKE installations to the latest patch version. Checked the availability with gcloud CLI on `us-east1` and `europe-centra2l` regions to make sure it is already available.

fix(gke): bump GKE kubernetes version

---

bootstrap/helm/bootstrap/Chart.yaml
bootstrap/helm/bootstrap/templates/azure.yaml
bootstrap/helm/bootstrap/values.yaml
bootstrap/plural/recipes/azure-cluster-api-migrate-test.yaml

During CAPI bootstrapping there is a conflict with creating the Azure AD Pod Identity resource and the installation of the CRD since that is done by the same chart, causing a classic chicken&egg problem. This PR allows us to disable creation of the resource during cluster bootstrapping where it isn't needed and causes problems. It also creates a second recipe that will allow us to properly test fresh Azure clusters deployed with CAPI.

fix(bootstrap): allow for disabling azure pod id creation

---

.github/workflows/matrix-vendor-and-publish.yml

This PR updates the Plural CLI used in our action to the latest version needed so charts with the new `chartInstalled` template function can be pushed once https://github.com/pluralsh/plural/pull/1248 is released.

chore: update plural CLI used in action

---

bootstrap/helm/cluster-api-cluster/Chart.yaml
bootstrap/helm/cluster-api-cluster/templates/_helpers.tpl
bootstrap/helm/cluster-api-cluster/tests/gcp_cluster_test.yaml
bootstrap/helm/cluster-api-cluster/tests/gcp_control_plane_test.yaml
bootstrap/helm/cluster-api-cluster/tests/gcp_machinepools_test.yaml
bootstrap/helm/cluster-api-cluster/values.yaml
bootstrap/helm/cluster-api-cluster/values.yaml.tpl

- add helm units tests for GCP provider
- move default kubernetes version from helper file to values template
Locally with link

fix: move kubernetes version to template and add gcp unit tests

---

.github/workflows/matrix-vendor-and-publish.yml
bootstrap/helm/cluster-api-bootstrap/Chart.yaml
bootstrap/helm/cluster-api-bootstrap/values.yaml
bootstrap/helm/cluster-api-control-plane/Chart.yaml
bootstrap/helm/cluster-api-control-plane/values.yaml
bootstrap/helm/cluster-api-core/Chart.yaml
bootstrap/helm/cluster-api-core/values.yaml
bootstrap/helm/cluster-api-provider-aws/Chart.yaml
bootstrap/helm/cluster-api-provider-aws/values.yaml
bootstrap/helm/cluster-api-provider-azure/Chart.yaml
bootstrap/helm/cluster-api-provider-azure/values.yaml
bootstrap/helm/cluster-api-provider-docker/Chart.yaml
bootstrap/helm/cluster-api-provider-docker/values.yaml
bootstrap/helm/cluster-api-provider-gcp/Chart.yaml
bootstrap/helm/cluster-api-provider-gcp/values.yaml

This PR ensures we use vendored images for `kubectl` in the CAPI charts so we avoid docker rate limits. It also updates the `setup-plural` action since the current version seems to be broken with newer versions of the CLI.

fix(bootstrap): use vendored kubectl image for CAPI

---

bootstrap/helm/bootstrap/Chart.yaml
bootstrap/helm/bootstrap/values.yaml

This PR allows us and users to disable the external-dns subchart.

fix(bootstrap): allow for disabling external dns

---

chatwoot/helm/chatwoot/Chart.yaml

The app version wasn't updated in the last update. This PR updates it so it doesn't confuse users.

fix(chatwoot): set correct app version

---

airflow/plural/docs/aws-secrets-backend.md

Docs for adding AWS Secrets Manager as a secrets backend on a Plural Airflow Instance
No test plan since it's just an `.md`
___
not sure that a lot of this applies since it's a doc for an existing application, but let me know if there's anything that I missed

docs: Add docs for connecting airflow to aws secrets backend

---

airflow/plural/docs/adjust-scheduler-resources.md

This should help your Airflow users understand how to update scheduler resources for Airflow hosted on plural.sh
I'm running the provided configuration in my plural.sh Airflow and it's working great 👍
___ 
A lot of the checklist items may not really apply since it's a simple doc, but let me know if there's anything else I can add 🍻

docs: Add a guide for adjusting airflow scheduler resources

---

airbyte/plural/docs/running-on-custom-nodes.md

If your customers want to run Airbyte workloads on a specific node type, this should get them started.
I'm using the documented configuration on my plural.sh hosted Airbyte and it's working great.
___
Checklist isn't very applicable because it's a simple doc add. Let me know if I missed anything 🍻

docs: Add a guide for running airbyte workloads on custom nodes

---

airflow/plural/docs/running-on-custom-nodes.md

Shows users how to point Airflow tasks at custom node groups
Currently running this in my plural.sh hosted Airflow and it's working great!
___
A lot of the checklist items don't feel applicable with this just being a doc add. Let me know if I missed anything! 🍻

docs: Add a guide for running airflow tasks on custom nodes

---

airflow/plural/docs/basic-auth.md

These docs will help your users utilize the Airflow Stable REST API for Airflow instances running on plural.sh
I've completed these steps on my plural.sh Airflow instance successfully.
___
Not sure if much of the checklist applies since it's just a doc add for an existing app - let me know if you want me to change anything 🍻

docs: Add docs for basic auth to airflow stable rest api

---

bootstrap/helm/bootstrap/Chart.yaml
bootstrap/helm/bootstrap/values.yaml.tpl
bootstrap/terraform/gcp-bootstrap/deps.yaml
bootstrap/terraform/gcp-bootstrap/main.tf
bootstrap/terraform/gcp-bootstrap/outputs.tf
bootstrap/terraform/gcp-bootstrap/variables.tf

It relies on terraform being executed first and removing `certmanager` SA. Then helm will recreate it with proper annotation and cert-manager deployment should get restarted thanks to new `checksum/sa` annotation.
Locally with link

feat(gcp): let helm manage certmanager SA instead of terraform

---

mimir/helm/mimir/Chart.yaml
mimir/helm/mimir/values.yaml.tpl
mimir/plural/recipes/mimir-gcp.yaml
mimir/terraform/gcp/deps.yaml
mimir/terraform/gcp/main.tf
mimir/terraform/gcp/outputs.tf
mimir/terraform/gcp/terraform.tfvars
mimir/terraform/gcp/variables.tf

Will use this to test grafana agent on our cd-demo cluster
local

feat: Add support for mimir on gcp

---

superset/helm/superset/Chart.yaml
superset/helm/superset/templates/reencrypt-secrets.yaml
superset/helm/superset/values.yaml
superset/helm/superset/values.yaml.tpl

Looks like this isn't set properly via the chart, setting ourselves manually here.
local link

feat: Override superset secret key

---

airflow/helm/airflow/Chart.yaml
airflow/helm/airflow/templates/statsd-exporter.yaml

The statsd exporter service used app.kubernetes.io/name twice
n/a

feat: Fix airflow double-labelling

---

kafka/helm/kafka/Chart.yaml
kafka/helm/kafka/templates/kafka.yaml

Allow pod template customizations on the strimzi kafka CRD. This will allow operators to set up `podAffinity` blocks and more.
A good use case for this feature is configuring all kafka/zookeper pods to run on different nodes: [strimzi docs](https://strimzi.io/docs/operators/0.35.1/full/configuring#configuring-pod-anti-affinity-to-schedule-each-kafka-broker-on-a-different-worker-node-str)

feat(kafka): allow pod template customizations

---

posthog/plural/recipes/posthog-azure.yaml

Create a recipe named posthog-azure.yaml in posthog/plural/recipes to add Azure provider for Posthog in the Plural marketplace.

chore: Add missing posthog-azure.yaml to add azure provider for Posthog

---

datadog/helm/datadog/Chart.yaml

Bump official DataDog chart version
2.36.1 → 3.59.4

feat(datadog): update datadog chart version

---

airflow/helm/airflow/Chart.yaml
airflow/helm/airflow/values.yaml.tpl

Later versions of airflow removed this function on us, but looks like we can just use a function bound to the jwt library itself directly.
n/a

fix: deprecated jwt decode method
