bootstrap/terraform/aws-bootstrap/deps.yaml, bootstrap/terraform/aws-bootstrap/main.tf, bootstrap/terraform/aws-bootstrap/output.tf, bootstrap/terraform/aws-bootstrap/variables.tf
=> New node groups step 1

influx/helm/influx/Chart.yaml, influx/helm/influx/values.yaml
=> fix using vendored images influx

bootstrap/helm/bootstrap/Chart.yaml, bootstrap/helm/bootstrap/values.yaml.tpl
=> use vendored calico images

vaultwarden/helm/vaultwarden/Chart.yaml, vaultwarden/helm/vaultwarden/values.yaml
=> use vaultwarden vendored image

bootstrap/terraform/aws-bootstrap/deps.yaml, bootstrap/terraform/aws-bootstrap/output.tf
Output the cluster OIDC issuer URL of EKS cluster
=> eks output cluster_oidc_issuer_url

airbyte/vendor_images
vendor airbyte images using new CI
=> vendor airbyte images

bootstrap/terraform/azure-bootstrap/deps.yaml, bootstrap/terraform/azure-bootstrap/main.tf, bootstrap/terraform/azure-bootstrap/variables.tf
Pin azure Kubernetes version with variable and set to a valid version.
=> azure bump to valid k8s version

argo-workflows/helm/argo-workflows/Chart.yaml, argo-workflows/helm/argo-workflows/templates/secret.yaml, argo-workflows/helm/argo-workflows/values.yaml.tpl, argo-workflows/terraform/azure/main.tf, argo-workflows/terraform/azure/outputs.tf, argo-workflows/terraform/azure/terraform.tfvars, argo-workflows/terraform/azure/variables.tf
Also needed for full test framework integration
Will test and fix forward based on integration with our azure cluster
=> Onboard argo workflows for azure

.gitignore, airflow/helm/airflow/runbooks/scaling-manual-webserver.xml, airflow/helm/airflow/runbooks/scaling-manual-worker.xml, airflow/helm/airflow/templates/dashboards.yaml, airflow/helm/airflow/templates/monitors.yaml, airflow/helm/airflow/templates/postgres.yaml, airflow/helm/airflow/templates/prometheusrule.yaml, airflow/helm/airflow/templates/proxies.yaml, airflow/helm/airflow/templates/runbooks.yaml, airflow/helm/airflow/templates/secrets.yaml, airflow/helm/airflow/templates/statsd-exporter.yaml, airflow/helm/airflow/values.yaml.tpl
Hello @michaeljguarino , we are currently using Airflow through Plural with the following modifications:
* We use Cloud SQL as our db
* We use Kubernetes Executor instead of Celery based one
* We have a custom GCS sync operator which utilizes existing PVC to sync dags
Based on these modifications we do not necessarily need Zalando Postgres, Redis, etc. instances. Therefore, I updated the helm templates to respect these variations.
I am new to Plural, so I would appreciate some feedback on this :)
=> airflow helm updates

airflow/helm/airflow/Chart.yaml, airflow/helm/airflow/templates/secrets.yaml, airflow/helm/airflow/templates/statsd-exporter.yaml, airflow/helm/airflow/values.yaml.tpl
There are still a few bugs related to postgres enabling in airflow, which this should fix.
tested via local link
=> Fix airflow deployment

airbyte/plural/recipes/airbyte-aws.yaml, airbyte/plural/recipes/airbyte-azure.yaml, airbyte/plural/recipes/airbyte-gcp.yaml, airbyte/plural/recipes/airbyte-kind.yaml, bootstrap/terraform/gcp-bootstrap/deps.yaml, bootstrap/terraform/gcp-bootstrap/main.tf, bootstrap/terraform/gcp-bootstrap/services.tf
need to enable compute service as well
plural link
=> Enable compute service too

airbyte/helm/airbyte/Chart.yaml, airbyte/helm/airbyte/templates/dashboards.yaml, airbyte/helm/airbyte/templates/postgres.yaml, airbyte/helm/airbyte/templates/prometheusrule.yaml, airbyte/helm/airbyte/templates/proxies.yaml, airbyte/helm/airbyte/templates/runbooks.yaml, airbyte/helm/airbyte/values.yaml, airbyte/helm/airbyte/values.yaml.tpl
Hello @michaeljguarino, similar to the Airflow case we are using an external db for our Airbyte deployment. I modified the helm templates to support that. I would appreciate if you could take a look.
=> airbyte helm updates

vaultwarden/helm/vaultwarden/Chart.yaml, vaultwarden/helm/vaultwarden/values.yaml.tpl
Adds email settings to our Vaultwarden deployment
=> add email to Vaultwarden

vaultwarden/helm/vaultwarden/Chart.yaml, vaultwarden/helm/vaultwarden/values.yaml, vaultwarden/helm/vaultwarden/values.yaml.tpl
Fixes the vaultwarden email setup and bumps the version.
=> fix vaultwarden email and bump version

kafka/helm/kafka/Chart.yaml, kafka/helm/kafka/templates/dashboards.yaml
Just fixed a typo in the Dashboard CR, which was causing an error in console. 
Tested locally using plural link
=> fix typo in kafka dashboard

.github/workflows/matrix-vendor-and-publish.yml
This will allow us to rely on gh releases as source of truth and pin specific CLI versions
tested locally via act
=> Use new setup plural action

kafka/helm/kafka/Chart.yaml, kafka/helm/kafka/templates/podmonitor.yaml, kafka/helm/kafka/templates/svc.yaml
Hey @michaeljguarino , as we discussed yesterday, you can find here my modifications to get Grafana dashboard for Kafka running. It is not templated yet but it should work nevertheless.
Local testing with plural link
=> kafka monitoring updates

grafana-tempo/helm/grafana-tempo/Chart.yaml, grafana-tempo/helm/grafana-tempo/values.yaml.tpl
This PR fixes getting the Redis password in the Grafana Tempo deployment.
=> fix getting redis password in tempo

renovate.json
This PR adds grouping of all helm related updates for all applications through Renovate.
=> add renovate grouping for all apps

ghost/helm/ghost/Chart.yaml, ghost/helm/ghost/values.yaml
There are a lot of new features abhi and brandon want to leverage there, in addition to potential community users
plural link
=> Update ghost to v5

hasura/helm/hasura/Chart.yaml, hasura/helm/hasura/templates/dashboards.yaml, hasura/helm/hasura/templates/postgres.yaml, hasura/helm/hasura/templates/prometheusrule.yaml, hasura/helm/hasura/templates/proxies.yaml, hasura/helm/hasura/templates/runbooks.yaml, hasura/helm/hasura/templates/secret.yaml, hasura/helm/hasura/values.yaml.tpl
Hello @michaeljguarino, we are currently onboarding Hasura and would like to use Cloud SQL as the Postgres db. I did some changes to support that. Could you take a look?
Local testing with plural link
=> update hasura chart to plug in cloud sql db

vault/helm/vault/Chart.yaml, vault/helm/vault/values.yaml.tpl, vault/terraform/gcp/deps.yaml, vault/terraform/gcp/main.tf, vault/terraform/gcp/output.tf, vault/terraform/gcp/terraform.tfvars, vault/terraform/gcp/variables.tf
Adds support for GCP to our Vault deployment.
Local linking. At the moment still untested.
=> Onboard Vault on GCP

airbyte/helm/airbyte/values.yaml
We've already vendored the appropriate images, this wires everything up.
tested using plural link
=> Upgrade airbyte to ~0.39

ghost/helm/ghost/templates/ingress.yaml, ghost/helm/ghost/templates/service.yaml, ghost/helm/ghost/values.yaml, ghost/helm/ghost/values.yaml.tpl
Make it possible to host ghost at subpath.
Local linking, still todo.
=> feat: Make it possible to host ghost at subpath

ghost/helm/ghost/Chart.yaml, ghost/helm/ghost/values.yaml
Update the image of our ghost deployment.
=> update ghost image

strapi/helm/strapi/Chart.yaml, strapi/helm/strapi/values.yaml
Strapi ingress configuration changes
=> 🔨 strapi ingress changes

metabase/helm/metabase/Chart.yaml, metabase/helm/metabase/values.yaml.tpl
Hello @michaeljguarino @DavidSpek, 
I have made a minor modification to the metabase chart so that we can use cloud sql instead of operator managed postgres. Could you please review this change?
Tested locally with plural link
=> add external db support for metabase

argo-workflows/helm/argo-workflows/Chart.yaml, argo-workflows/helm/argo-workflows/templates/artifact-repositories-cm.yaml
=> fix argo workflows config

bootstrap/helm/bootstrap/Chart.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_configurationoverlays.platform.plural.sh.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_dashboards.platform.plural.sh.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_defaultstorageclasses.platform.plural.sh.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_licenses.platform.plural.sh.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_logtails.platform.plural.sh.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_proxies.platform.plural.sh.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_registrycredentials.platform.plural.sh.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_resourcegroups.platform.plural.sh.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_runbooks.platform.plural.sh.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_secretsyncs.platform.plural.sh.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_slashcommands.platform.plural.sh.yaml, bootstrap/helm/bootstrap/crds/apiextensions.k8s.io_v1_customresourcedefinition_statefulsetresizes.platform.plural.sh.yaml, bootstrap/helm/bootstrap/templates/rbac.yaml, bootstrap/helm/bootstrap/values.yaml
Bump plural-operator to v0.3.5
=> bump plural-operator to v0.3.5

bootstrap/helm/bootstrap/Chart.yaml, bootstrap/helm/bootstrap/values.yaml
The configmap and secret reloader implementation has problems so reverting to the old controller image for now.
Linked the artifact locally and deployed to a cluster.
=> revert to previous operator image

bootstrap/plural/recipes/azure-k8s.yaml, bootstrap/terraform/azure-bootstrap/deps.yaml, bootstrap/terraform/azure-bootstrap/main.tf, bootstrap/terraform/azure-bootstrap/terraform.tfvars, bootstrap/terraform/azure-bootstrap/variables.tf
Replaces: https://github.com/pluralsh/plural-artifacts/pull/315
Local linking with upgrading existing cluster and deploying a new cluster.
=> Azure bootstrap improvements v2

datahub/repository.yaml
=> Update Datahub description

airflow/helm/airflow/Chart.yaml, airflow/helm/airflow/values.yaml
dbt wasn't working because git isn't actually installed in the image, modified it and now wiring it in
plural link, verified airflow still healthy
=> Use new airflow image

ray/helm/ray/Chart.yaml, ray/helm/ray/templates/raycluster-cluster.yaml, ray/helm/ray/values.yaml
Adds the ability to set the image for ray workers.
=> add ability to set ray worker image

argo-cd/helm/argo-cd/Chart.yaml, argo-cd/plural/recipes/argo-cd-aws.yaml, argo-cd/plural/recipes/argo-cd-azure.yaml, argo-cd/plural/recipes/argo-cd-gcp.yaml
Change `argo-cd` `credentialPassword` for password type.
=> ENG-781 change argo-cd credentialPassword for password type

.github/workflows/docker.yml, airflow/Dockerfile
Will help us support airflow 2.2.5
=> Bump airflow docker image

airflow/helm/airflow/Chart.yaml, airflow/helm/airflow/values.yaml
This will allow processes within airflow to update the git filesystem (eg for dbt operations)
tested via link, and touched a few files to ensure editing worked
=> Change gid/uid for airflow git sync

prefect/helm/prefect/Chart.yaml, prefect/helm/prefect/values.yaml.tpl
This seems to have been hardcoded previously which is no-bueno
destroyed our setup, then used a link
=> Fix prefect postgres password setup

monitoring/helm/monitoring/Chart.yaml, monitoring/helm/monitoring/values.yaml, monitoring/terraform/aws/deps.yaml, monitoring/terraform/aws/main.tf, monitoring/terraform/aws/variables.tf, monitoring/vendor_images.yaml
i think there's something wrong with the vendoring, just use gcr for now then fix
=> Monitoring fix

postgres/plural/docs/backup-restore.md, postgres/repository.yaml
This can be useful for disaster recovery and is just a general reliability box-check
n/a
=> Add docs for postgres backup/restore

bootstrap/helm/bootstrap/Chart.yaml, bootstrap/helm/bootstrap/templates/issuer.yaml, bootstrap/helm/bootstrap/values.yaml, monitoring/helm/monitoring/Chart.yaml, monitoring/helm/monitoring/values.yaml
for some reason this isn't vendored properly at the moment, this will fix
link
=> Gcr opentelemetry

prefect/plural/docs/getting-started.md
- Adds getting started guide to Prefect artifact
=> Add Prefect getting started guide

n8n/helm/n8n/Chart.yaml, n8n/helm/n8n/values.yaml
Update the n8n release to 0.213.0. Introducing new features and bugfixes
https://docs.n8n.io/reference/release-notes/
NA
=> Update n8n release to 0.213.0

bootstrap/terraform/aws-bootstrap/aws-lb-controller.tf, bootstrap/terraform/aws-bootstrap/deps.yaml
use fix suggested here: https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/2692#issuecomment-1160444064
in progress
=> Fix aws loadbalancer iam policy

airflow/helm/airflow/Chart.yaml, airflow/helm/airflow/templates/statsd-exporter.yaml, airflow/helm/airflow/values.yaml, airflow/vendor_images.yaml, trino/plural/docs/adding-catalogs.md, trino/repository.yaml
This is a manual step so if we can at least point to it, that could help
n/a
=> Add docs for configuring trino catalogs

bootstrap/terraform/gcp-bootstrap/deps.yaml, bootstrap/terraform/gcp-bootstrap/variables.tf
Our previous one was deprecated
link
=> Use newer gke version

Makefile, README.md
I just realized there isn't an appropriate readme for this repo.  We should add one to foster external contribution
n/a
=> Add readme

clickhouse/terraform/kube/deps.yaml, mongodb/terraform/kube/deps.yaml
didn't add the appropriate providers
n/a
=> Fix mongodb terraform

mongodb/terraform/kube/deps.yaml
=> fix mongodb deps

gitlab/helm/gitlab/Chart.yaml, gitlab/helm/gitlab/values.yaml.tpl, gitlab/plural/notes.tpl, gitlab/terraform/gcp/deps.yaml, gitlab/terraform/gcp/main.tf
looks like this is using a miswired input
n/a
=> Fix GCP gitlab setup

sftpgo/plural/recipes/sftpgo-azure.yaml, sftpgo/plural/recipes/sftpgo-kind.yaml, sftpgo/terraform/kube/deps.yaml, sftpgo/terraform/kube/terraform.tfvars, sftpgo/terraform/kube/variables.tf
- Fixed sftpgo gcp dependency
- Added kind provider
- Removed useless tf variables
=> fix: fix sftpgo gcp dependency + kind provider

clickhouse/plural/docs/exposing-via-loadbalancer.md, clickhouse/plural/docs/setup.md, clickhouse/repository.yaml
Explains how to use load balancer service and create an initial crd
=> Add docs for clickhouse setup

airbyte/helm/airbyte/Chart.yaml, airbyte/helm/airbyte/values.yaml, airflow/helm/airflow/Chart.yaml, airflow/helm/airflow/values.yaml.tpl
looks like this might fix some ui flakes, so good to get out
local link
=> Upgrade airbyte to v0.42.0

loki/helm/loki/Chart.yaml, loki/helm/loki/deps.yaml, loki/plural/recipes/loki-aws.yaml, loki/plural/recipes/loki-azure.yaml, loki/plural/recipes/loki-gcp.yaml
needed to expose it on a hostname now
n/a
=> Add loki ingress dependency

tier/helm/tier/Chart.yaml, tier/helm/tier/deps.yaml, tier/helm/tier/values.yaml.tpl, tier/plural/notes.tpl, tier/plural/recipes/tier-aws.yaml, tier/plural/recipes/tier-azure.yaml, tier/plural/recipes/tier-gcp.yaml, tier/terraform/kube/main.tf
This PR fixes the [failed deployment](https://github.com/pluralsh/plural-artifacts/actions/runs/4559430914/jobs/8043383803) because it doesn't have notes.tpl. It also adds ingress to tier.
=> feat: add notes.tpl & ingress to tier

tier/helm/tier/Chart.yaml, tier/helm/tier/runbooks/scaling-manual.xml, tier/helm/tier/templates/deployment.yaml, tier/helm/tier/templates/ingress-basic-auth.yaml, tier/helm/tier/templates/runbooks.yaml, tier/helm/tier/templates/secrets.yaml, tier/helm/tier/values.yaml, tier/helm/tier/values.yaml.tpl, tier/plural/notes.tpl, tier/plural/recipes/tier-aws.yaml, tier/plural/recipes/tier-azure.yaml, tier/plural/recipes/tier-gcp.yaml
Finished implementation for tier.
A few questions:
1. Is there an example dashboard that I can re-use for tier?
2. I'm not sure I've addressed the secrets correctly, both the stripe API key that needs to be input as well as the basic auth key that's generated upon install
1. Create a live and test key in stripe
3. Configure tier with live=false and use the live stripe key
4. Configure tier with live=true and use the test stripe key
5. If the pod runs, it means it can talk to stripe correctly. Alternatively you can run `curl -u "{{.Values.tier.basicAuth }}:" https://{{ .Values.hostname }}`
=> feat: tier with protected ingress

sftpgo/plural/notes.tpl, sftpgo/plural/recipes/sftpgo-aws.yaml, sftpgo/plural/recipes/sftpgo-azure.yaml, sftpgo/plural/recipes/sftpgo-gcp.yaml, sftpgo/plural/recipes/sftpgo-kind.yaml, sftpgo/repository.yaml
=> SFTPGo: fix name, add a link to the website

redis/plural/docs/external-hostname.md, redis/plural/recipes/aws-redis.yaml, redis/plural/recipes/azure-redis.yaml, redis/plural/recipes/gcp-redis.yaml, redis/repository.yaml
people always fill them in even if they mostly shouldn't, just use in-app docs to explain the ingress config
n/a
=> Don't ask for redis hosts in recipe

loki/helm/loki/Chart.yaml, loki/helm/loki/values.yaml.tpl
I believe this should solve the conditional logic for loki
n/a
=> Fix loki templating

elasticsearch/plural/notes.tpl
Explains how to extract the password, and prints the kibana hostname
n/a
=> feat(elasticsearch): improve post install notes

bootstrap/terraform/azure-bootstrap/deps.yaml, bootstrap/terraform/azure-bootstrap/main.tf, bootstrap/terraform/azure-bootstrap/variables.tf
needed to help unblock azure users w/ tagging policies
local link
=> feat: Add tags to azure resources

directus/helm/directus/Chart.yaml
Bump directus version to test OIDC
=> chore(directus): bump version

directus/helm/directus/Chart.yaml, directus/helm/directus/values.yaml.tpl, directus/plural/recipes/directus-aws.yaml, directus/plural/recipes/directus-azure.yaml, directus/plural/recipes/directus-gcp.yaml
- Add SMTP config for Directus (https://docs.directus.io/self-hosted/config-options.html#email)
=> feat(directus): add smtp config

bootstrap/helm/bootstrap-operator/Chart.yaml, bootstrap/helm/bootstrap-operator/values.yaml
=> fix: fix bootstrap operator tag

bootstrap/helm/bootstrap-operator/Chart.yaml, bootstrap/helm/bootstrap-operator/crds/bootstrap.plural.sh_bootstraps.yaml, bootstrap/helm/bootstrap-operator/templates/bootstrap.yaml, bootstrap/helm/bootstrap-operator/values.yaml
add an option to skip cluster creation
=> feat: add an option to skip cluster creation

README.md
explain the terms of the contributor program and how to get your appropriate reward.
n/a
=> Add contributor program details

.github/workflows/docker.yml, dagster/helm/dagster/Chart.yaml, dagster/helm/dagster/values.yaml
- Fix dagster dockerfile image
=> fix(dagster-gcp): fix dagster user code docker image

sonarqube/helm/sonarqube/Chart.yaml, sonarqube/helm/sonarqube/values.yaml
- For some reason, CI/CD pushed image sonarqube to `dkr.plural.sh/sonarqube/library/sonarqube`
=> fix(sonarqube): fix docker image

.github/workflows/docker.yml, dagster/helm/dagster/Chart.yaml, dagster/helm/dagster/values.yaml
- Fix dagter image, hopefully final fix
=> fix(dagster): fix dagster dkr image

dagster/helm/dagster/Chart.yaml, weaviate/helm/weaviate/Chart.yaml, weaviate/helm/weaviate/values.yaml, weaviate/helm/weaviate/values.yaml.tpl, weaviate/plural/notes.tpl, weaviate/plural/recipes/weaviate-aws.yaml, weaviate/plural/recipes/weaviate-azure.yaml, weaviate/plural/recipes/weaviate-gcp.yaml
- Add authentification layer (api key)
- fix weaviate service account by rerouting recipes to correct terraform modules
- Local tf link
=> feat(weaviate): add auth + fix weaviate terraform modules

bootstrap/helm/bootstrap-operator/Chart.yaml, bootstrap/helm/bootstrap-operator/values.yaml.tpl
=> fix: Update bootstrap operator templating

bootstrap/terraform/aws-bootstrap-cluster-api/deps.yaml, bootstrap/terraform/aws-bootstrap-cluster-api/main.tf, bootstrap/terraform/aws-bootstrap-cluster-api/variables.tf, bootstrap/terraform/gcp-bootstrap-cluster-api/deps.yaml, bootstrap/terraform/gcp-bootstrap-cluster-api/main.tf, bootstrap/terraform/gcp-bootstrap-cluster-api/terraform.tfvars, bootstrap/terraform/gcp-bootstrap-cluster-api/variables.tf
update terraform for cluster api
=> refactor: update terraform for cluster api

bootstrap/helm/bootstrap-operator/Chart.yaml, bootstrap/helm/bootstrap-operator/templates/bootstrap.yaml, bootstrap/helm/bootstrap-operator/values.yaml
bump bootstrap operator version
=> chore: bump bootstrap operator version

n8n/helm/n8n/Chart.yaml, n8n/helm/n8n/runbooks/scaling-manual.xml, n8n/helm/n8n/templates/runbook.yaml
The scaling for this is somewhat complex so an app-level runbook is probably warranted
link
=> feat: Bake n8n scaling runbook

bootstrap/helm/bootstrap-operator/Chart.yaml, bootstrap/helm/bootstrap-operator/crds/bootstrap.plural.sh_bootstraps.yaml, bootstrap/helm/bootstrap-operator/values.yaml, bootstrap/helm/bootstrap-operator/values.yaml.tpl
=> perf: bump bootstrap operator

bootstrap/terraform/azure-bootstrap/deps.yaml, bootstrap/terraform/azure-bootstrap/variables.tf
Upgrade Azure AKS version to 1.24.10
=> chore: Upgrade Azure AKS version to 1.24.10

prefect-worker/helm/prefect-worker/Chart.yaml, prefect-worker/helm/prefect-worker/templates/_helpers.tpl
- Add template file for scale up runbook (fixes lint issue)
- Bump version
=> fix: prefect worker template file

README.md
=> fix: Typo fix in readme

prefect-agent/helm/prefect-agent/Chart.yaml, prefect-agent/helm/prefect-agent/values.yaml, prefect-worker/helm/prefect-worker/Chart.yaml, prefect-worker/helm/prefect-worker/values.yaml, prefect-worker/plural/recipes/prefect-worker-aws.yaml, prefect-worker/plural/recipes/prefect-worker-azure.yaml, prefect-worker/plural/recipes/prefect-worker-gcp.yaml, prefect/helm/prefect/Chart.yaml, prefect/helm/prefect/values.yaml
- Bump Prefect image ref in chart (and subsequently bump chart)
- Add workPool string input (populates: https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-worker/values.yaml#L39)
=> chore: Update prefect worker inputs & update prefect versions

prefect-worker/helm/prefect-worker/Chart.yaml, prefect-worker/helm/prefect-worker/values.yaml, prefect-worker/helm/prefect-worker/values.yaml.tpl, prefect-worker/repository.yaml
Makes the prefect-worker app public
Bump chart version
Fix workPool ref being lowercase
Beta release status
=> chore: public prefect-worker app

airbyte/helm/airbyte/Chart.yaml, airbyte/helm/airbyte/values.yaml
=> fix(airbyte): upgrade to v0.44.8

meilisearch/repository.yaml, sonarqube/plural/recipes/sonarqube-aws.yaml, sonarqube/plural/recipes/sonarqube-azure.yaml, sonarqube/plural/recipes/sonarqube-gcp.yaml, sonarqube/repository.yaml, unleash/helm/unleash/Chart.yaml, unleash/helm/unleash/values.yaml.tpl, unleash/plural/recipes/unleash-aws.yaml, unleash/plural/recipes/unleash-azure.yaml, unleash/plural/recipes/unleash-gcp.yaml, unleash/repository.yaml
This was being templated as a yaml int, which is not valid for env var values
link
=> fix: fix unleash smtp port

directus/plural/docs/bring-your-own-postgres.md, directus/repository.yaml
Simple documentations for bringing existing postgres dbs.
n/a
=> feat: Directus byodb docs

airbyte/helm/airbyte/Chart.yaml, airbyte/helm/airbyte/runbooks/scaling-manual.xml, airbyte/helm/airbyte/templates/runbooks.yaml, airbyte/helm/airbyte/values.yaml
Captures some common scaling challenges with airbyte
link
=> feat: Add scaling runbook/config overlay for airbyte

directus/helm/directus/Chart.yaml, directus/helm/directus/values.yaml.tpl, directus/plural/recipes/directus-aws.yaml, directus/plural/recipes/directus-azure.yaml, directus/terraform/aws/deps.yaml, directus/terraform/aws/main.tf, directus/terraform/aws/terraform.tfvars, directus/terraform/aws/variables.tf
Needed to persist files durably
local links
=> feat: Add directus s3 support

rabbitmq/plural/notes.tpl, rabbitmq/repository.yaml
Helps users understand how to connect to rabbitmq
n/a
=> fix(rabbitmq): rabbitmq notes

bin/artifact-renovate-script.sh, renovate.json
This PR updates the renovate configuration and the script that generates it.
=> ci: update renovate config file

elasticsearch/helm/elasticsearch/Chart.yaml, elasticsearch/helm/elasticsearch/templates/es-ingess.yaml, elasticsearch/helm/elasticsearch/values.yaml, elasticsearch/plural/docs/external-ingress.md, elasticsearch/repository.yaml
Can be needed for some valid ES usecases
link
=> Support external ingress for elasticsearch too

metabase/helm/metabase/Chart.yaml, metabase/helm/metabase/values.yaml
This includes the relevant fix for the metabase vulnerability I believe
link
=> fix: Upgrade to v0.46.6.1

airbyte/helm/airbyte/Chart.yaml, airbyte/helm/airbyte/values.yaml, sentry/helm/sentry/Chart.yaml, sentry/helm/sentry/values.yaml
we've left this behind for a bit, so getting up to date
local link
=> feat: Upgrade airbyte to 0.50.8

cube/repository.yaml, cube/terraform/aws/deps.yaml, cube/terraform/aws/iam.tf, imgproxy/repository.yaml, neo4j/repository.yaml
Fixes issue with IRSA and publishes the app publicly.  Also adds neo4j/imgproxy
links
=> feat: publish cubejs to BETA

airflow/helm/airflow/Chart.yaml, airflow/helm/airflow/values.yaml, airflow/helm/airflow/values.yaml.tpl
our containers repo has had this image built and users are pulling it down already, so need to get it out there.
local link
=> feat: Update airflow to 2.6.3

tempo/plural/recipes/tempo-aws.yaml, tempo/plural/recipes/tempo-azure.yaml, tempo/plural/recipes/tempo-gcp.yaml
The recipes were still marked as private. This PR fixes that.
=> fix(tempo): mark recipes as public

sysbox/terraform/aws/deps.yaml, sysbox/terraform/aws/main.tf
=> fix(sysbox): add ns back

umami/helm/umami/Chart.yaml, umami/helm/umami/values.yaml
=> fix(umami): fix docker image

bootstrap/terraform/azure-bootstrap/deps.yaml, bootstrap/terraform/azure-bootstrap/variables.tf
Tested by deploying first bootstrap, then console. DNS was really slow, but everything works after a while.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205250531521725
=> feat: Bump Azure Kubernetes version to 1.25.11

airbyte/helm/airbyte/Chart.yaml, airbyte/helm/airbyte/runbooks/scaling-manual.xml
the action button wasn't actually included
link
=> fix: Fix airbyte runbook

retool/helm/retool/Chart.yaml, retool/helm/retool/deps.yaml, retool/helm/retool/values.yaml
Breaking update to update retool major version to 3.4.x
local link
=> Upgrade retool to 3.4.14

appsmith/helm/appsmith/Chart.yaml, appsmith/helm/appsmith/values.yaml.tpl, backstage/helm/backstage/Chart.yaml
fixes some small issues with both apps
link
=> fix: Fix small appsmith/backstage issues

bootstrap/helm/cluster-api-cluster/Chart.yaml, bootstrap/helm/cluster-api-cluster/values.yaml
this PR fixes docker CAPI cluster deployment
=> fix: Docker capi cluster

dagster/helm/dagster/Chart.yaml
Trying to solve [action error](https://github.com/pluralsh/plural-artifacts/actions/runs/6588546208/job/17901059931#step:9:58)
=> fix(dagster): bump dagster helm vsn

chatwoot/helm/chatwoot/Chart.yaml, chatwoot/helm/chatwoot/values.yaml, retool/helm/retool/Chart.yaml, retool/helm/retool/values.yaml
=> feat: Bump chatwoot + retool again

bootstrap/terraform/aws-bootstrap/deps.yaml, bootstrap/terraform/aws-bootstrap/variables.tf
Also updates the kube proxy addon version appropriately too
local link in an aws cluster and plan
=> feat: Update EKS to 1.25

rabbitmq/helm/cluster-operator/Chart.yaml, rabbitmq/helm/cluster-operator/templates/pdb.yaml
=> fix: Fix PodDisruptionBudget reference

airflow/helm/airflow/Chart.yaml, airflow/helm/airflow/values.yaml
Remove empty pools
causing issues w/ new airflows vsn (and is uneccessary)
=> feat: Sync pools empty

retool/helm/retool/Chart.yaml, retool/helm/retool/values.yaml
Has a few important fixes users have mentioned.
local link
=> feat: Upgrade retool to 3.33.6

chatwoot/helm/chatwoot/Chart.yaml, chatwoot/helm/chatwoot/values.yaml
A few minor vsns behind
local link
=> feat: Bump chatwoot to 3.7.0

.github/CODEOWNERS, retool/helm/retool/Chart.yaml, retool/helm/retool/values.yaml
Keeping up w/ latest releases
n/a
=> feat: Bump retool to 3.52.1

directus/helm/directus/Chart.yaml
=> Update directus to 9.26.0
